"""replace user age with padel level

Revision ID: a4ed4a7f3ff6
Revises: 5d9764689aea
Create Date: 2026-08-03 20:54:45.989994

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'a4ed4a7f3ff6'
down_revision: str | None = '5d9764689aea'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Float(), nullable=True))
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.INTEGER(), nullable=True))
        batch_op.drop_column('level')

    # ### end Alembic commands ###
