"""event format, roster visibility

Revision ID: e7adba966e95
Revises: b3197bddbf9a
Create Date: 2026-08-13 18:46:11.968645

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'e7adba966e95'
down_revision: str | None = 'b3197bddbf9a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table('events', schema=None) as batch_op:
        # server_default именем члена, а не значением: SQLAlchemy читает
        # эту колонку как имя ('SINGLES'), и 'singles' сломал бы чтение
        # уже существующих мероприятий.
        batch_op.add_column(
            sa.Column(
                'format',
                sa.Enum(
                    'SINGLES', 'DOUBLES',
                    name='eventformat', native_enum=False, length=16,
                ),
                server_default='SINGLES',
                nullable=False,
            )
        )
        # Прежние мероприятия состав не показывали, но и настройки такой не
        # было — включаем, это новое поведение по умолчанию.
        batch_op.add_column(
            sa.Column('show_roster', sa.Boolean(), server_default='1', nullable=False)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('show_roster')
        batch_op.drop_column('format')

    # ### end Alembic commands ###
